ocaml-doc/voodoo

- src/voodoo-do/do.ml
- src/voodoo-gen/bin/main.ml
- src/voodoo-gen/generator.ml
- src/voodoo-gen/hrefs.ml
- src/voodoo-gen/link.ml
- src/voodoo-gen/metadata.ml
- src/voodoo-prep/main.ml
- src/voodoo-prep/opam.ml
- src/voodoo/do.ml
- src/voodoo/error_log.ml
- src/voodoo/version.ml
Rough and ready PR to create a page with the error log on when `voodoo-do` is invoked with `--failed`
> Produce pages when failures are encountered

- src/voodoo-gen/package_info.ml
Basically I considered only the parent module name in the `children` map so that would be incorrect if two modules have the same name anywhere in the hierarchy. Or even a stack overflow when one is a children of the other.
> fix how the module tree is computed

- src/voodoo/package_info.ml
Voodoo needs to be consistent about the URL where it serves the module docs of a library and the URL where it requests them. For the serve URL, it always uses the module structure as given by dune. However, for the request URL, it used to use an unwrapped version of the module structure whenever the library doesn't have an explicit library interface. That's why this commit removes that unwrapping of the module structure.
Side-note: We're quite confident that the distinction we've removed was only introduced by copying code from the context of the version index page. On the version index page, it makes sense to have that distinction: if a library doesn't have a library interface, all its modules are exposed and so it's desirable to have all its modules on the index page and not only the …
> Fix module docs link in library with no explicit interface

- dune-project
- src/voodoo-gen/bin/main.ml
- src/voodoo-gen/markdown.ml
- src/voodoo-gen/rendering.ml
- voodoo-gen.opam
- voodoo-gen.opam.template
This is my attempt at addressing https://github.com/ocaml/ocaml.org/issues/30
Some packages (e.g [base](https://github.com/janestreet/base/blob/master/README.org)) don't use Markdown but the `org-mode` syntax for their `readme`. 
Even if on the `ocaml.org` side we support showing a `README.org` file, the HTML output is not nice:
To improve that, we could create our own `org` parser or re-use an existing one, https://github.com/whirm/mlorg or https://github.com/logseq/mldoc for example. Correct me if I'm wrong, but I don't think that creating our own parser or re-using an existing one (supposing that it would fit our needs) would be trivial. Even if we manage to produce an AST, we would still have to transform it to HTML format.
That's why I chose to use `pandoc`. `.org` files are …
> use pandoc to parse .org files

- src/voodoo-gen/generator.ml
- src/voodoo-gen/generator.mli
- src/voodoo-gen/link.ml
- src/voodoo-gen/link.mli
- src/voodoo-gen/markdown.ml
- src/voodoo-gen/rendering.ml
- voodoo-gen.opam
- voodoo-gen.opam.template
Reverts ocaml-doc/voodoo#39 because it is not ready to go in the live pipeline yet.
> Revert "use odoc html --as-json to bring back the missing preambles"

- voodoo-gen.opam
The pin for odoc on the pipeline makes `odoc` install as `dev`, so voodoo will only be able to require exact versions after the pipeline no longer pins odoc.
> odoc must be lower bound as long as pipeline pins odoc

- dune-project
- src/voodoo-do/do.ml
- src/voodoo-gen/bin/main.ml
- voodoo-do.opam
- voodoo-gen.opam
(And leave the odoc version choice to the pipeline - we'll get that sorted out later)
> artificially bump do and gen

- src/voodoo-gen/bin/main.ml
- src/voodoo-gen/odoc_thtml.ml
- src/voodoo-gen/search_index.ml
This PR makes voodoo generate a search index by traversing the `.odocl` files, outputting a javascript file creating an index for the fuse-js library.
When this is ultimately done by `odoc` itself, we can remove this code.
Made with @sabine!
> Generate a fuse index for search

- .ocamlformat
- dune-project
- voodoo-do.opam
- voodoo-gen.opam
- voodoo-gen.opam.template
Remove the need to pin this version in [ocaml-docs-ci](https://github.com/ocurrent/ocaml-docs-ci).
> Pin odoc.2.2.0 version.

- src/voodoo-gen/search_index.ml
Simple expansions were ignored during the traverse of `.odocl` file (introduced in #58), resulting in an incomplete search index.
> Fix incomplete search index

- .ocamlformat
- dune-project
- voodoo-do.opam
- voodoo-gen.opam
This reverts commit dbd9b7d9b2c14fd0119bf2a0992936cd480fa9d9 in line with https://github.com/ocurrent/ocaml-docs-ci/pull/116. We'll disentangle voodoo and the pipeline on the staging environment first.
> Revert "Pin odoc.2.2.0 version."

- src/voodoo-gen/dune
In https://github.com/ocaml-doc/voodoo/commit/be10e78f8af15633a868f2c5e9deb7b807df4788, I accidentally removed `voodoo_lib` from `voodoo-gen/dune`.
> Add voodoo_lib in dune libraries

- dune
- dune-project
- src/voodoo/do.ml
- test/uninstalled_package.t
- voodoo-do.opam
- voodoo-lib.opam
- voodoo-prep.opam
Fix #38
Catch the `Not_found` exception, and use a Result type instead of an Option to carry the error message.
Needs to be rebased on #65
> Clean error when running voodoo-do on an uninstalled package

- src/voodoo-prep/dune
- src/voodoo-prep/main.ml
- src/voodoo-prep/main.mli
- src/voodoo-prep/prep.ml
- src/voodoo-prep/prep.mli
Extracted from #62
Just swapping the content `src/voodoo-prep/main.ml` and `src/voodoo-prep/prep.ml`
> Make main the top-level module in voodoo-prep

- dune
Trying to fix this error on the CI:
```
File "dune", line 1, characters 0-84:
1 | (rule
2 |  (with-stdout-to
3 |   dune-project.1
4 |   (run dune format-dune-file dune-project)))
(cd _build/default && /Users/runner/work/voodoo/voodoo/_opam/bin/dune format-dune-file dune-project) > _build/default/dune-project.1
Error: /Users/runner/work/voodoo/voodoo/_build/default/dune-project: No such
file or directory
Error: Process completed with exit code 1.
```
From the "CI / build-and-test" check
> CI: mark dune-project as a dependence of the fmt rule

- dune-project
- src/voodoo-gen/dune
- src/voodoo-gen/main.ml
- src/voodoo-gen/package_info.ml
- src/voodoo/dune
- src/voodoo/package_info.ml
- voodoo-gen.opam
- voodoo-lib.opam
`ppx_deriving_yojson` is older but it allows us to drop the `base` dependency.
> Replace ppx_yojson_conv with ppx_deriving_yojson

- src/voodoo-gen/main.ml
- test/can-render-org-files.t
- test/can-render-tables.t
Suggested by @sabine
Based on #67 to simplify writing in the package.json file
> List "other" doc files info (README, LICENSE, CHANGES) in status.json

- dune-project
- src/voodoo-do/do.ml
- src/voodoo-do/dune
- src/voodoo/dune
- src/voodoo/dune.ml
- src/voodoo/dune.mli
- src/voodoo/mld.ml
- src/voodoo/util.ml
- voodoo-do.opam
- voodoo-gen.opam
- voodoo-lib.opam
- voodoo-prep.opam
This reverts commit e8f0c37da4216324d284adaa9b39368206ac870c.
@sabine this keeps the "ocaml >= 4.08" constraint for voodoo-gen only. We need to use something else to have access to `Result` that doesn't exist in the stdlib before, so I've used `Bos_setup.R` which is already available since we already depend on `bos`.
> Remove "ocaml >= 4.08" dependency on voodoo-lib, voodoo-do and voodoo-prep

- src/voodoo-prep/main.ml
- src/voodoo-prep/prep.ml
- src/voodoo-prep/prep.mli
Option `-L` is not used by ocaml-docs-ci, and the lib-dir is straight up ignored by `Prep.run` anyway.
> voodoo-prep: Simplify voodoo-prep cli, remove option `-L`

- src/voodoo-do/do.ml
- src/voodoo-do/do.mli
- src/voodoo-do/main.ml
- src/voodoo/opam.ml
- src/voodoo/opam.mli
Option `-p` is always used so let's make it required and remove the `run_all` function, that allows us to drop a lot of opam stuff
> voodoo-do: Simplify voodoo-do cli, make `-p` required

- src/voodoo-gen/dune
- src/voodoo-gen/main.ml
- src/voodoo-gen/markdown.ml
- src/voodoo-gen/package_info.ml
- src/voodoo-gen/rendering.ml
- src/voodoo-gen/search_index.ml
Normalizing according to the rest, voodoo-prep and voodoo-do already use this type.
> voodoo-gen: Use Bos_setup.R

- src/voodoo-gen/markdown.ml
`Soft_break` in markdown rendering (see README/LICENSE/CHANGELOG files) was turned into a `Linebreak` in the generated odoc document.
This resulted in unwanted line breaks in the emitted HTML documents.
This patch changes rendering to instead emit a space character.
> Change Soft_break to emit space character in markdown renderer
